#!/bin/bash

# Cette fonction permet de faire un arbre du dossier récursivement
#
# $1 racine du dossier à lister
# $2 dossier à lister récursivement
function browse {
    for fichier in $(ls -A $2)
    do
        if [ $fichier != '.sync' ]; then
            echo $2/$fichier
            if [ -d $2/$fichier ]; then
                browse $1 $2/$fichier
            fi
        fi
    done
}

# Cette fonction permet de générer un journal
#
# $1 dossier synchronisé
function journalisation {
    dossier=$(readlink -f $1)
    journal=""
    journal_path=$dossier/.sync/journal
    journal_temp=""

    # Faire un arbre de fichier
    arborescence=$(browse $dossier $dossier | sed -e "s@^$dossier/@@g")
    # Faire un journal
    for fichier in $arborescence
    do
        if ! [ -d $fichier ]; then
            md5=$(md5sum $fichier | cut -d" " -f1)
        else
            md5=""
        fi
        journal_temp+="${fichier};${md5}"
        journal_temp+=$'\n'
    done
    echo "$journal_temp"
}

# Cette fonction permet de générer le rapport de synchronisation
#
# $1 dossier synchronisé
function diff {
    dossier=$1
    if [ -d $dossier ]; then
        if [ -d $dossier/.sync ]; then
            journal_path=$dossier/.sync/journal
            journal=$(cat $journal_path)
            journal_temp=$(journalisation $dossier)

            for ligne in $journal_temp
            do
                fichier=$(echo $ligne | cut -d';' -f1)
                if [ "$(echo $journal | egrep "${fichier};")" = "" ]; then
                    echo "[ADD]$fichier"
                fi
            done
            for ligne in $journal
            do
                fichier=$(echo $ligne | cut -d';' -f1)
                if [ "$(echo $journal_temp | egrep "${fichier};")" = "" ]; then
                    echo "[REM]$fichier"
                fi
            done
            for ligne in $journal_temp
            do
                fichier=$(echo $ligne | cut -d';' -f1)
                md5=$(echo $ligne | cut -d';' -f2)
                ligne_journal=$(cat $journal_path | grep "^${fichier};")
                md5_journal=$(echo $ligne_journal | cut -d';' -f2)
                # On évite les nouveaux fichiers
                if [ "$md5_journal" != "" ]; then
                    if [ "$md5" != "$md5_journal" ]; then
                        echo "[MOD]$fichier"
                    fi
                fi
            done
        else
            echo "[ERR] Le dossier n'est pas synchronisé."
        fi
    else
        echo "[ERR] Le dossier n'existe pas."
    fi
}

if [ $# -gt 1 ]; then
    commande=$1
    if [ $commande = "get" ]; then
        journalisation $2
    elif [ $commande = "diff" ]; then
        diff $2
        exit
    fi
else
    echo "[ERR] Il n'y a pas assez d'arguments transmis."
fi
