#!/bin/bash

# Cette fonction permet de faire un arbre du dossier récursivement
#
# $1 dossier à lister récursivement
function browse {
    for fichier in $(ls -A $1)
    do
        if [ $fichier != '.sync' ]; then
            if [ -d $1/$fichier ]; then
                echo "${1}/${fichier}"
                browse $1/$fichier
            else
                echo "${1}/${fichier}"
            fi
        fi
    done
}

# Cette fonction permet de générer un journal
#
# $1 dossier synchronisé
function journalisation {

    dossier=$1
    journal=""
    journal_path=$dossier/.sync/journal
    journal_temp=""

    # Faire un arbre de fichier
    arborescence=$(browse $dossier)
    # Faire un journal
    for fichier in $arborescence
    do
        if ! [ -d $fichier ]; then
            md5=$(md5sum $fichier | cut -d" " -f1)
        else
            md5=""
        fi
        journal_temp+="${fichier}---${md5}"
        journal_temp+=$'\n'
    done
    echo "$journal_temp"
    

}

# Cette fonction permet de générer le rapport de synchronisation
#
# $1 dossier synchronisé
function diff {
    dossier=$1
    if [ -d $dossier ]; then
        if [ -d $dossier/.sync ]; then
            journal=$(cat $dossier/.sync/journal)
            journal_actuel=$(journalisation $dossier)
            # Faire un fichier diff
            #   Fichiers ajoutés
            #   Fichiers supprimés
            #   Fichiers édités
        else
            echo "[ERR] Le dossier n'est pas synchronisé."
        fi
    else
        echo "[ERR] Le dossier n'existe pas."
    fi
}

if [ $# -gt 1 ]; then
    commande=$1
    if [ $commande = "get" ]; then
        journalisation $2
    elif [ $commande = "diff" ]; then
        diff $2
        exit
    fi
else
    echo "[ERR] Il n'y a pas assez d'arguments transmis."
fi
