#!/bin/bash

# Cette fonction retourne le chemin relatif d'un module du projet
function get_lib {
    echo "$(dirname $0)/$1"
}

# Cette fonction détecte les conflits
#
# Attention elle va uniquement dans un sens (local -> distant)
# et nécéssite un autre appel qui fera (distant -> local)
#
# $1 dossier synchronisé
function detecter_conflit {
    local=$1
    distant=$(cat $1/.sync/remote)

    journal_path=$(get_lib journal)
    conflits=""

    # On génère les différences
    diff_local_path="${local}/.sync/diff"
    $journal_path diff $local > $diff_local_path
    diff_distant_path="${distant}/.sync/diff"
    $journal_path diff $distant > $diff_distant_path

    for diff in $(cat $diff_local_path)
    do
        status=$(echo $diff | cut -d"#" -f1)
        fichier=$(echo $diff | cut -d"#" -f2)
        # Les fichiers créés
        if [ "$status" == "ADD" ]; then
            # Si le fichier a été créé dans les deux dossiers
            if [ "$(cat $diff_distant_path | egrep "^(ADD|${fichier})")" != "" ]; then
                # Si le fichier a le même nom qu'un dossier
                if [[ (-f $local/$fichier && -d $distant/$fichier) || (-d $local/$fichier && -f $distant/$fichier) ]]; then
                    echo "FichierMemeNomQueDossier>${fichier}"
                # Si les fichiers ne sont pas identiques
                else
                    if [ "$(md5sum $local/$fichier)" != "$(md5sum $distant/$fichier)"]; then
                        echo "DeuxFichiersCreesMemeContents>${fichier}"
                    else
                        echo "DeuxFichiersCrees>${fichier}"
                    fi
                fi
            fi
        # Les fichiers supprimés
        elif [ "$status" == "REM" ]; then
            # Si le fichier a été supprimé et modifié dans les deux dossiers
            if [ "$(cat $diff_distant_path | egrep "^(MOD#${fichier})")" != "" ]; then
                echo "SuppEtMod>${fichier}"
            fi
        # Les fichiers modifiés
        elif [ "$status" == "MOD" ]; then
            # Si les deux fichiers ont été édités
            if [ "$(cat $diff_distant_path | egrep "^(MOD#${fichier})")" != "" ]; then
                echo "DeuxModDiff>${fichier}"
            fi
        fi
    done
}


if [ $# -gt 1 ]; then
    if [ $1 == 'conflits' ]; then
        detecter_conflit $2
        exit
    fi

    if [ $1 == 'sync' ]; then
        date
        exit
    fi
else
    echo "[ERR] Veuillez transmettre au moins un argument."
fi
