#!/bin/bash

# Cette fonction retourne le chemin relatif d'un module du projet
function get_lib {
    echo "$(dirname $0)/$1"
}

# Cette fonction détecte les conflits
#
# Attention elle va uniquement dans un sens (local -> distant)
# et nécéssite un autre appel qui fera (distant -> local)
#
# $1 dossier synchronisé
function detecter_conflit {
    local=$1
    distant=$(cat $1/.sync/remote)

    journal_path=$(get_lib journal)
    conflits=""

    # On génère les différences
    diff_local_path="${local}/.sync/diff"
    $journal_path diff $local > $diff_local_path
    diff_distant_path="${distant}/.sync/diff"
    $journal_path diff $distant > $diff_distant_path

    # cas 1 --> Les deux fichiers ont été modifié depuis la dernière synchro.
    # cas 2 --> un fichier à le même nom qu'un répertoire
    # cas 3 --> Si le fichier a été modifié en local et supprimer en distant
    # cas 4 --> Si le fichier a été modifié en distant et supprimer en local
    # cas 5 --> Deux fichier ont été crée avec le même nom

    for diff in $(cat $diff_local_path)
    do
        status=$(echo $diff | cut -d"#" -f1)
        fichier=$(echo $diff | cut -d"#" -f2)
        # Les fichiers créés
        if [ "$status" == "ADD" ]; then
            # Si le fichier a été créé dans les deux dossiers
            if [ "$(cat $diff_distant_path | egrep "^(ADD|${fichier})")" != "" ]; then
                # Si le fichier a le même nom qu'un dossier
                if [[ (-f $local/$fichier && -d $distant/$fichier) || (-d $local/$fichier && -f $distant/$fichier) ]]; then
                    echo "2>${fichier}"
                # Si ce sont deux fichiers
                else
                    echo "5>${fichier}"
                fi
            fi
        # Les fichiers supprimés
        elif [ "$status" == "REM" ]; then
            # Si le fichier a été supprimé et modifié dans les deux dossiers
            if [ "$(cat $diff_distant_path | egrep "^(MOD#${fichier})")" != "" ]; then
                echo "4>${fichier}"
            fi
        # Les fichiers modifiés
        elif [ "$status" == "MOD" ]; then
            # Si les deux fichiers ont été édités
            if [ "$(cat $diff_distant_path | egrep "^(MOD#${fichier})")" != "" ]; then
                echo "1>${fichier}"
            fi
        fi
    done
}


if [ $# -gt 1 ]; then
    if [ $1 == 'conflits' ]; then
        detecter_conflit $2
        exit
    fi

    if [ $1 == 'sync' ]; then
        date
        exit
    fi
else
    echo "[ERR] Veuillez transmettre au moins un argument."
fi
